{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: {{ .Values.prometheus.servicePort }}
      targetPort: {{ .Values.prometheus.servicePort }}
  type: ClusterIP
{{- end }}
