grafana:
  enabled: true
  image: grafana/grafana
  tag: latest
  servicePort: 3000
  ingress:
    enabled: true
    path: /grafana(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
    serve_from_sub_path: true

prometheus:
  enabled: true
  image: prom/prometheus
  tag: latest
  servicePort: 9090
  ingress:
    enabled: true
    host: prometheus.local

loki:
  enabled: true
  image: grafana/loki
  tag: latest
  servicePort: 3100
  ingress:
    enabled: true
    path: /loki(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

  server:
    http_path_prefix: /loki
